---
blank_issues_enabled: false
contact_links:
  - name: GitHubBackupTool Community Support
    url: https://github.com/michaelmsonne/GitHubBackupTool/discussions
    about: Please ask and answer questions here.
